/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFormDialog: typeof import('./src/components/common/AddFormDialog/AddFormDialog.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu/AppMenu.vue')['default']
    AreaForm: typeof import('./src/components/Areas/AreaForm.vue')['default']
    AreaList: typeof import('./src/components/Areas/AreaList.vue')['default']
    CardComponent: typeof import('./src/components/common/CardComponent/CardComponent.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconUnsplash: typeof import('./src/components/icons/IconUnsplash.vue')['default']
    ProjectForm: typeof import('./src/components/Projects/ProjectForm.vue')['default']
    ProjectList: typeof import('./src/components/Projects/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusFilter: typeof import('./src/components/common/StatusFilter/StatusFilter.vue')['default']
    TaskForm: typeof import('./src/components/Tasks/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/Tasks/TaskList.vue')['default']
    UnsplashGallery: typeof import('./src/components/common/Unsplash/UnsplashGallery.vue')['default']
    UnsplashWidget: typeof import('./src/components/common/Unsplash/UnsplashWidget.vue')['default']
  }
}
